#pragma once
#include "common.h"

#define CALL_DBGLEVEL 2
#define ARG_DBGLEVEL 2

#define ARG_DECLARE(TYPE, NAME)\
    TYPE &NAME = *((TYPE*)(&(args[arg_index])));\
    arg_index+=sizeof(TYPE);\
    DBG_PRINTVAR(ARG_DBGLEVEL,NAME);\

#define COMMAND_FUNCTION_DEF0(NAME)\
    [](uint8_t args[8]){\
    DBG_PRINTLN(CALL_DBGLEVEL,"Command called: "#NAME);\

#define COMMAND_FUNCTION_DEF1(NAME, TYPE0, NAME0)\
    COMMAND_FUNCTION_DEF0(NAME)\
    uint8_t arg_index=0;\
    ARG_DECLARE(TYPE0, NAME0)\

#define COMMAND_FUNCTION_DEF2(NAME, TYPE0, NAME0, TYPE1, NAME1)\
    COMMAND_FUNCTION_DEF1(NAME, TYPE0, NAME0)\
    ARG_DECLARE(TYPE1, NAME1)\

#define COMMAND_FUNCTION_DEF3(NAME, TYPE0, NAME0, TYPE1, NAME1, TYPE2, NAME2)\
    COMMAND_FUNCTION_DEF2(NAME, TYPE0, NAME0, TYPE1, NAME1)\
    ARG_DECLARE(TYPE2, NAME2)\

#define COMMAND_FUNCTION_DEF4(NAME, TYPE0, NAME0, TYPE1, NAME1, TYPE2, NAME2, TYPE3, NAME3)\
    COMMAND_FUNCTION_DEF3(NAME, TYPE0, NAME0, TYPE1, NAME1, TYPE2, NAME2)\
    ARG_DECLARE(TYPE3, NAME3)

extern void (*(commands[256]))(uint8_t[8]);